# Generated by Django 2.2.7 on 2019-12-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20191125_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='portrait_name',
        ),
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar'),
        ),
    ]
